const emojiToTextMap = {
    '😊': ['happy', 'joy', 'content', 'delighted'],
    '😂': ['laugh', 'lol', 'hilarious', 'funny'],
    '❤️': ['love', 'heart', 'affection', 'fond'],
    '😢': ['sad', 'tearful', 'upset', 'crying'],
    '👍': ['thumbs up', 'approval', 'well done', 'good job'],
    '🔥': ['fire', 'lit'],
    '🥵': ['hot', 'attractive', 'sexy'],
    '🙏': ['thank you', 'thanks', 'appreciation', 'gratitude'],
    '🎉': ['celebration', 'festivity', 'cheer'],
    '🥳': ['celebrate', 'party', 'joyful', 'festive'],
    '😎': ['cool', 'awesome', 'chill', 'smooth'],
    '🤗': ['hug', 'embrace', 'comfort', 'cuddle'],
    '🤔': ['thinking', 'pondering', 'wondering', 'curious'],
    '😜': ['silly', 'playful', 'mischievous'],
    '😏': ['smirk', 'sly', 'sneaky'],
    '🤓': ['nerd', 'glasses'],
    '🤯': ['mind blown', 'shocked', 'amazed', 'astonished'],
    '😑': ['irritated', 'irritate', 'annoy', 'annoying'],    
    '💀': ['dead', 'skull', 'death', 'end'],
    '👀': ['side eye', 'looking', 'observing', 'staring'],
    '💩': ['poop', 'crap', 'waste', 'dung', 'useless'],
    '✨': ['sparkles', 'shiny', 'glimmer'],
    '😤': ['triumph', 'proud', 'victory', 'success'],
    '😱': ['scream', 'scared', 'terrified'],
    '🤪': ['crazy', 'wild', 'wacky'],
    '🤡': ['joker', 'dumb'],
    '👻': ['ghost', 'spooky', 'spirit', 'phantom'],
    '😈': ['devil', 'evil', 'wicked'],
    '😇': ['angel', 'innocent', 'pure', 'holy'],
    '💔': ['broken heart', 'heartbreak', 'sadness', 'loss'],
    '😅': ['nervous laugh', 'awkward', 'embarrassed', 'sheepish'],
    '🥺': ['pleading', 'begging', 'imploring', 'asking'],
    '🥴': ['drunk', 'woozy', 'intoxicated'],
    '🤑': ['money mouth', 'rich', 'greedy', 'cash'],
    '🤭': ['secrecy', 'shhh', 'quiet', 'hush'],
    '💪': ['strong', 'powerful', 'muscular', 'fit'],
    '🤝': ['handshake', 'agreement', 'deal', 'partnership'],
    '💫': ['dizzy', 'spinning', 'disoriented', 'confused'],
    '🌟': ['star', 'bright', 'shiny', 'famous'],
    '💣': ['bomb'],
    '🎆': ['fireworks', 'firecrackers'],
    '🎶': ['music', 'melody', 'tune', 'song'],
    '🎃': ['halloween', 'pumpkin'],
    '🎄': ['christmas', 'x-mas'],
    '🎁': ['gift', 'gifts'],
    '🍕': ['pizza', 'slice'],
    '🚀': ['rocket', 'launch', 'space', 'blast off'],
    '🌈': ['rainbow', 'colors', 'pride', 'spectrum'],
    '🎂': ['birthday', 'cake', 'anniversary'],
    '🌍': ['earth', 'world', 'planet', 'globe'],
    '🏆': ['trophy', 'win', 'winner', 'award', 'champion'],
    '👑': ['king', 'queen', 'royalty', 'crown'],
    '💡': ['idea', 'thought', 'innovation', 'inspiration'],
    '🌞': ['sun', 'warm', 'sunny'],
    '🌧️': ['rain', 'drizzle', 'storm', 'weather'],
    '⛄': ['snowman', 'winter', 'cold', 'snow'],
    '🍔': ['burger', 'food', 'meal', 'fast food'],
    '☕': ['coffee', 'caffeine', 'beverage'],
    '🍫': ['chocolate', 'candy', 'sweet'],
    '🌸': ['flowers', 'blossom', 'bloom', 'blooms'],
    '🌹': ['rose', 'roses', 'flower'],
    '📚': ['books', 'reading', 'study', 'learn'],
    '✈️': ['plane', 'travel', 'flight', 'trip'],
    '🏠': ['house', 'home', 'building', 'residence'],
    '🔑': ['key', 'unlock', 'access', 'open'],
    '📅': ['calendar', 'schedule', 'date', 'event'],
    '🧁': ['cupcake', 'dessert', 'treat'],
    '😡': ['angry', 'mad', 'furious'],
    '👋': ['hi', 'hello', 'wave', 'greeting'],
    '🤖': ['robot', 'machine', 'bot', 'android'],
    '🧸': ['teddy', 'teddy bear', 'soft toy', 'bear'],
    '🌳': ['tree', 'trees', 'nature', 'outdoors', 'outside'],
    '🐶': ['dog', 'puppy', 'canine', 'pet'],
    '🐱': ['cat', 'kitten', 'feline'],
    '🦁': ['lion', 'animal'],
    '🐦': ['bird', 'chirp', 'avian', 'fly'],
    '🍎': ['apple', 'fruit', 'healthy'],
    '🍌': ['banana'],
    '🍇': ['grapes', 'vine'],
    '🍉': ['watermelon', 'summer'],
    '🍷': ['wine', 'red wine'],
    '🍺': ['beer', 'alcohol', 'brew'],
    '🍹': ['mojito', 'cocktail', 'drink'],
    '🍵': ['green tea', 'tea'],
    '⚽': ['soccer', 'football', 'sports'],
    '🏀': ['basketball', 'game', 'hoops'],
    '🌕': ['moon', 'full moon', 'night'],
    '💙': ['blue', 'blue heart'],
    '💚': ['green', 'green heart'],
    '💛': ['yellow', 'yellow heart'],
    '💜': ['purple', 'purple heart'],
};

const textToEmojiMap = {
    'happy': '😊', 'joy': '😊', 'content': '😊', 'delighted': '😊',
    'hi': '👋', 'hello': '👋', 'wave': '👋', 'greeting': '👋',
    'laugh': '😂', 'lol': '😂', 'hilarious': '😂', 'funny': '😂',
    'love': '❤️', 'heart': '❤️', 'affection': '❤️', 'fond': '❤️',
    'sad': '😢', 'tearful': '😢', 'upset': '😢', 'crying': '😢',
    'thumbs up': '👍', 'approval': '👍', 'well done': '👍', 'good job': '👍',
    'fire': '🔥', 'lit': '🔥',
    'hot': '🥵', 'attractive': '🥵', 'sexy': '🥵',
    'thank you': '🙏', 'thanks': '🙏', 'appreciation': '🙏', 'gratitude': '🙏',
    'celebration': '🎉', 'festivity': '🎉', 'cheer': '🎉',
    'celebrate': '🥳', 'joyful': '🥳', 'festive': '🥳', 'party': '🥳',
    'cool': '😎', 'awesome': '😎', 'chill': '😎', 'smooth': '😎',
    'hug': '🤗', 'embrace': '🤗', 'comfort': '🤗', 'cuddle': '🤗',
    'thinking': '🤔', 'pondering': '🤔', 'wondering': '🤔', 'curious': '🤔',
    'silly': '😜', 'playful': '😜', 'mischievous': '😜',
    'smirk': '😏', 'sly': '😏', 'sneaky': '😏',
    'nerd': '🤓', 'glasses': '🤓',
    'mind blown': '🤯', 'shocked': '🤯', 'amazed': '🤯', 'astonished': '🤯',
    'irritated': '😑', 'irritate': '😑', 'annoy': '😑', 'annoying': '😑',
    'dead': '💀', 'skull': '💀', 'death': '💀', 'end': '💀',
    'side eye': '👀', 'looking': '👀', 'observing': '👀', 'staring': '👀',
    'poop': '💩', 'crap': '💩', 'waste': '💩', 'dung': '💩', 'useless': '💩',
    'sparkles': '✨', 'shiny': '✨', 'glimmer': '✨',
    'triumph': '😤', 'proud': '😤', 'victory': '😤', 'success': '😤',
    'scream': '😱', 'scared': '😱', 'terrified': '😱',
    'crazy': '🤪', 'wild': '🤪', 'wacky': '🤪',
    'joker': '🤡', 'dumb': '🤡',
    'ghost': '👻', 'spooky': '👻', 'spirit': '👻', 'phantom': '👻',
    'devil': '😈', 'evil': '😈', 'wicked': '😈',
    'angel': '😇', 'innocent': '😇', 'pure': '😇', 'holy': '😇',
    'broken heart': '💔', 'heartbreak': '💔', 'sadness': '💔', 'loss': '💔',
    'nervous laugh': '😅', 'awkward': '😅', 'embarrassed': '😅', 'sheepish': '😅',
    'pleading': '🥺', 'begging': '🥺', 'imploring': '🥺', 'asking': '🥺',
    'drunk': '🥴', 'woozy': '🥴', 'intoxicated': '🥴',
    'money mouth': '🤑', 'rich': '🤑', 'greedy': '🤑', 'cash': '🤑',
    'secrecy': '🤭', 'shhh': '🤭', 'quiet': '🤭', 'hush': '🤭',
    'strong': '💪', 'powerful': '💪', 'muscular': '💪', 'fit': '💪',
    'handshake': '🤝', 'agreement': '🤝', 'deal': '🤝', 'partnership': '🤝',
    'dizzy': '💫', 'spinning': '💫', 'disoriented': '💫', 'confused': '💫',
    'star': '🌟', 'bright': '🌟', 'famous': '🌟',
    'bomb': '💣',
    'fireworks': '🎆', 'firecrackers': '🎆',
    'music': '🎶', 'melody': '🎶', 'tune': '🎶', 'song': '🎶',
    'halloween': '🎃', 'pumpkin': '🎃',
    'christmas': '🎄', 'x-mas': '🎄',
    'gift': '🎁', 'gifts': '🎁',
    'pizza': '🍕', 'slice': '🍕',
    'soccer': '⚽', 'football': '⚽', 'sports': '⚽',
    'basketball': '🏀', 'game': '🏀', 'hoops': '🏀',
    'rocket': '🚀', 'launch': '🚀', 'space': '🚀', 'blast off': '🚀',
    'rainbow': '🌈', 'colors': '🌈', 'pride': '🌈', 'spectrum': '🌈',
    'birthday': '🎂', 'cake': '🎂', 'anniversary': '🎂',
    'earth': '🌍', 'world': '🌍', 'planet': '🌍', 'globe': '🌍',
    'trophy': '🏆', 'win':'🏆', 'winner': '🏆', 'award': '🏆', 'champion': '🏆',
    'king': '👑', 'queen': '👑', 'royalty': '👑', 'crown': '👑',
    'idea': '💡', 'thought': '💡', 'innovation': '💡', 'inspiration': '💡',
    'sun': '🌞', 'warm': '🌞', 'sunny': '🌞',
    'rain': '🌧️', 'storm': '🌧️', 'drizzle': '🌧️', 'weather': '🌧️',
    'snowman': '⛄', 'winter': '⛄', 'cold': '⛄', 'snow': '⛄',
    'burger': '🍔', 'meal': '🍔', 'food': '🍔', 'fast food': '🍔',
    'coffee': '☕', 'caffeine': '☕', 'beverage': '☕',
    'chocolate': '🍫', 'candy': '🍫', 'sweet': '🍫',
    'flowers': '🌸', 'blossom': '🌸', 'bloom': '🌸', 'blooms': '🌸',
    'rose': '🌹', 'roses': '🌹', 'flower': '🌹',
    'books': '📚', 'reading': '📚', 'study': '📚', 'learn': '📚',
    'plane': '✈️', 'travel': '✈️', 'flight': '✈️', 'trip': '✈️',
    'house': '🏠', 'home': '🏠', 'building': '🏠', 'residence': '🏠',
    'key': '🔑', 'unlock': '🔑', 'access': '🔑', 'open': '🔑',
    'calendar': '📅', 'schedule': '📅', 'date': '📅', 'event': '📅',
    'cupcake': '🧁', 'dessert': '🧁', 'treat': '🧁',
    'angry': '😡', 'mad': '😡', 'furious': '😡',
    'robot': '🤖', 'machine': '🤖', 'bot': '🤖', 'android': '🤖',
    'teddy': '🧸', 'teddy bear': '🧸', 'soft toy': '🧸', 'bear': '🧸',
    'tree': '🌳', 'trees': '🌳', 'nature': '🌳', 'outdoors': '🌳', 'outside': '🌳',
    'dog': '🐶', 'puppy': '🐶', 'canine': '🐶', 'pet': '🐶',
    'cat': '🐱', 'kitten': '🐱', 'feline': '🐱',
    'lion': '🦁', 'animal': '🦁',
    'bird': '🐦', 'chirp': '🐦', 'avian': '🐦', 'fly': '🐦',
    'apple': '🍎', 'fruit': '🍎', 'healthy': '🍎',
    'banana': '🍌',
    'grapes': '🍇', 'vine': '🍇',
    'watermelon': '🍉', 'summer': '🍉',
    'wine': '🍷', 'red wine': '🍷',
    'beer': '🍺', 'alcohol': '🍺', 'brew': '🍺',
    'mojito': '🍹', 'cocktail': '🍹', 'drink': '🍹',
    'green tea': '🍵', 'tea': '🍵',
    'moon': '🌕', 'full moon': '🌕', 'night': '🌕',
    'blue heart': '💙', 'green heart': '💚', 'yellow heart': '💛', 'purple heart': '💜',
    'blue': '💙', 'green': '💚', 'yellow': '💛', 'purple': '💜',
};

export const emojiToText = (text) => {
    if (!text) return '';
    return text.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|[\uD83C-\uDBFF\uDC00-\uDFFF]+)/g, (match) => {
        const words = emojiToTextMap[match];
        return words ? words[0] : match; // Choose the first synonym as default
    });
};

export const textToEmoji = (text) => {
    if (!text) return '';

    // Dynamically create a regex pattern from textToEmojiMap keys
    const keys = Object.keys(textToEmojiMap).map(escapeRegExp).join('|');
    const regex = new RegExp(`\\b(${keys})\\b`, 'gi'); // Case-insensitive match

    // Replace matches with the corresponding emoji
    return text.replace(regex, (match) => textToEmojiMap[match.toLowerCase()] || match);
};

// Helper function to escape special regex characters
const escapeRegExp = (string) => {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
};
